src/Entity/Factura.php
<?php

namespace App\Entity;

use App\Repository\FacturaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FacturaRepository::class)]
class Factura implements \JsonSerializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $tipus = null;

    #[ORM\Column(length: 255)]
    private ?string $num_factura = null;

    #[ORM\Column(type: "decimal", precision: 10, scale: 2)]
    private ?string $preu = null;

    #[ORM\Column(type: "integer")]
    private ?int $quantitat = null;

    #[ORM\ManyToOne(inversedBy: 'factures')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Client $client = null;

    #[ORM\OneToMany(targetEntity: Obra::class, mappedBy: 'factura')]
    private Collection $obres;

    public function __construct()
    {
        $this->obres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTipus(): ?string
    {
        return $this->tipus;
    }

    public function setTipus(?string $tipus): void
    {
        $this->tipus = $tipus;
    }

    public function getNumFactura(): ?string
    {
        return $this->num_factura;
    }

    public function setNumFactura(?string $num_factura): void
    {
        $this->num_factura = $num_factura;
    }

    public function getPreu(): ?float
    {
        return $this->preu;
    }

    public function setPreu(?float $preu): void
    {
        $this->preu = $preu;
    }

    public function getQuantitat(): ?int
    {
        return $this->quantitat;
    }

    public function setQuantitat(?int $quantitat): void
    {
        $this->quantitat = $quantitat;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): static
    {
        $this->client = $client;
        return $this;
    }

    public function getObres(): Collection
    {
        return $this->obres;
    }

    public function addObra(Obra $obra): static
    {
        if (!$this->obres->contains($obra)) {
            $this->obres->add($obra);
            $obra->setFactura($this);
        }

        return $this;
    }

    public function removeObra(Obra $obra): static
    {
        if ($this->obres->removeElement($obra)) {
            if ($obra->getFactura() === $this) {
                $obra->setFactura(null);
            }
        }

        return $this;
    }

    public function jsonSerialize(): mixed
    {
        return [
            "id" => $this->getId(),
            "tipus" => $this->tipus,
            "num_factura" => $this->num_factura,
            "preu" => $this->preu,
            "quantitat" => $this->quantitat,
            "client" => $this->client?->getId(),
            // Només id per a evitar bucle
            "obres" => array_map(fn($obra) => $obra->getId(), $this->obres->toArray()),
        ];
    }
}

src/Form/FacturaType.php
<?php

namespace App\Form;

use App\Entity\Client;
use App\Entity\Factura;
use App\Entity\Obra;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FacturaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('tipus')
            ->add('num_factura')
            ->add('preu')
            ->add('quantitat')
            ->add('client', EntityType::class, [
                'class' => Client::class,
                'label' => 'client',
                'choice_label' => 'nom',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('obres', EntityType::class, [
                'class' => Obra::class,
                'label' => 'Obra',
                'choice_label' => 'nom',
                'attr' => ['class' => 'form-control'],
                'multiple' => true,
                'expanded' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Factura::class,
        ]);
    }
}

src/Controller/FacturaController.php
<?php

namespace App\Controller;

use App\Entity\Factura;
use App\Form\FacturaType;
use App\Repository\FacturaRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/factura')]
final class FacturaController extends AbstractController
{
    #[Route(name: 'app_factura_index', methods: ['GET'])]
    public function index(Request $request, PaginatorInterface $paginator, FacturaRepository $facturaRepository): Response
    {
        /* Paginador i cercador */
        $q = $request->query->get('q', '');

        if (empty($q))
            $query = $facturaRepository->findAllQuery();
        else
            $query = $facturaRepository->findByTextQuery($q);

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            15
        );

        return $this->render('factura/index.html.twig', [
            'q' => $q,
            'pagination' => $pagination,
            'facturas' => $pagination->getItems(),
        ]);
    }

    #[Route('/new', name: 'app_factura_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $factura = new Factura();
        $form = $this->createForm(FacturaType::class, $factura);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Obtindre dades del formulari
            $factura = $form->getData();

            // Recuperar entitat Obra
            $obrasSeleccionadas = $form->get('nom')->getData();

            // Obtindre info client
            $client = $factura->getClient();

            // Obtindre camps no mapejats
            $cognom = $request->request->get('factura')['cognom'];
            $correu = $request->request->get('factura')['correu'];

            // Assignació no temporal
            $factura->setCognom($cognom);
            $factura->setCorreu($correu);

            // Obres amb factures
            foreach ($obrasSeleccionadas as $obra) {
                $factura->addObra($obra);
            }

            $entityManager->persist($factura);
            $entityManager->flush();

            return $this->redirectToRoute('app_factura_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('factura/new.html.twig', [
            'factura' => $factura,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_factura_show', methods: ['GET'])]
    public function show(Factura $factura): Response
    {
        return $this->render('factura/show.html.twig', [
            'factura' => $factura,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_factura_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Factura $factura, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FacturaType::class, $factura);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_factura_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('factura/edit.html.twig', [
            'factura' => $factura,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_factura_delete', methods: ['POST'])]
    public function delete(Request $request, Factura $factura, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$factura->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($factura);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_factura_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/factura/_delete_form.html.twig
<form method="post" action="{{ path('app_factura_delete', {'id': factura.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ factura.id) }}">
    <button class="btn">Delete</button>
</form>

templates/factura/_form.html.twig
{{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': 'novalidate'}}) }}
<div class="container">
    <div class="row">
        <div class="col-3 mb-5">
            {{ form_row(form.tipus, {'label': 'Tipo'}) }}
        </div>
        <div class="col-3 mb-5">
            {{ form_row(form.num_factura, {'label': 'Nº factura'}) }}
        </div>
        <div class="col-3 mb-5">
            {{ form_row(form.client, {'label': 'Nombre de cliente'}) }}
        </div>
        <div class="col-3 mb-5">
            {{ form_row(form.obres, {'label': 'Título de la obra'}) }}
        </div>
        <div class="col-3 mb-5">
            {{ form_row(form.preu, {'label': 'Preu'}) }}
        </div>
        <div class="col-3 mb-5">
            {{ form_row(form.quantitat, {'label': 'Quantitat'}) }}
        </div>
    </div>
</div>
{{ form_widget(form) }}
<div class="container py-5">
    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-between">
                <a class="btn btn-rosa" href="{{ path('app_factura_index') }}">Volver</a>
                <button class="btn btn-outline-success">{{ button_label|default('Actualizar') }}</button>
            </div>
        </div>
    </div>
</div>
{{ form_end(form) }}

templates/factura/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Factura{% endblock %}

{% block body %}
    <h1>Edit Factura</h1>

    {{ include('factura/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_factura_crontroller_index') }}">back to list</a>

    {{ include('factura/_delete_form.html.twig') }}
{% endblock %}

templates/factura/index.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Gestionar Facturas{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <h2 class=" fs-3 py-5">Lista de facturas</h2>
            </div>
        </div>
    </div>

    <div class="container pb-5">
        <div class="row">
            <div class="col-12">
                <div class="d-flex justify-content-center align-items-center">
                    <form method="get" role="search" class="d-flex">
                        <input type="search" class="form-control rounded-start-pill" name="q"
                               aria-label="Search" placeholder="Bucar factura...">
                        <button type="submit" class="btn btn-rosa rounded-end-pill"><i class="bi bi-search"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table table-hover text-center">
                    <thead class="table-danger">
                    <tr>
                        <th class="d-none">Id</th>
                        <th class="d-none">Tipo</th>
                        <th>Nº Factura</th>
                        <th>Seudónimo</th>
                        <th>Título</th>
                        <th>Acción</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for factura in facturas %}
                        <tr>
                            <td class="d-none">{{ factura.id }}</td>
                            <td class="d-none">{{ factura.tipus }}</td>
                            <td>{{ factura.numFactura }}</td>
                            <td>
                                {% if factura.client %}
                                    {{ factura.client.pseudonim }}
                                {% else %}
                                    <span class="text-danger">Sin cliente</span>
                                {% endif %}
                            </td>
                            <td>
                                {% for obra in factura.obres %}
                                    {{ obra.nom }}{% if not loop.last %}, {% endif %}
                                {% else %}
                                    Sin obras asociadas
                                {% endfor %}
                            </td>
                            <td>
                                <a class="btn btn-success" href="{{ path('app_factura_show', {'id': factura.id}) }}"><i
                                            class="bi bi-eye"></i></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="4">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="navigation d-flex justify-content-center py-5">
        {{ knp_pagination_render(pagination) }}
    </div>

{% endblock %}

templates/factura/new.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Añadir Facturas{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <h2 class=" fs-3 py-5">Añadiendo una factura</h2>
            </div>
        </div>
    </div>

    {{ include('factura/_form.html.twig') }}

{% endblock %}

templates/factura/show.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Mostrar Facturas{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <h2 class=" fs-3 py-5">Viendo una factura</h2>
            </div>
        </div>
    </div>

    <div class="container d-flex justify-content-center text-center">
        <div class="row">
            <div class="col-12">
                <table class="table table-hover">
                    <tbody>
                    <tr class="d-none">
                        <th>Id</th>
                        <td>{{ factura.id }}</td>
                    </tr>
                    <tr>
                        <th class="table-warning">Número de la factura</th>
                        <td>{{ factura.numFactura }}</td>
                    </tr>
                    <tr>
                        <th class="table-warning">Nombre</th>
                        <td>{{ factura.client.nom }}</td>
                    </tr>
                    <tr>
                        <th class="table-warning">Apellido</th>
                        <td>{{ factura.client.cognom }}</td>
                    </tr>
                    <tr>
                        <th class="table-warning">Seudónimo</th>
                        <td>
                            {% if factura.client %}
                                {{ factura.client.pseudonim }}
                            {% else %}
                                <span class="text-danger">Sin cliente</span>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <th class="table-warning">Tipo</th>
                        <td>{{ factura.tipus }}</td>
                    </tr>
                    {% for obra in factura.obres %}
                        <tr>
                            <th class="table-warning">Título</th>
                            <td>{{ obra.nom }}</td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="2">No hay obras asociadas a esta factura.</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <th class="table-warning">Cantidad de obras</th>
                        <td>{{ factura.quantitat }}</td>
                    </tr>
                    <tr>
                        <th class="table-warning">Precio</th>
                        <td>{{ factura.preu }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="container d-flex justify-content-center pt-5">
        <div class="row">
            <div class="col-12">
                <a class="btn btn-rosa" href="{{ path('app_factura_index') }}">Volver</a>
            </div>
        </div>
    </div>

    <!--{{ include('factura/_delete_form.html.twig') }}-->
{% endblock %}