src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use JsonSerializable;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\InheritanceType("JOINED")]
#[ORM\DiscriminatorColumn(name: "rol", type: "string")]
#[ORM\DiscriminatorMap(["user" => User::class, "admin" => Administrador::class, "treballador" => Treballador::class, "client" => Client::class])]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface, JsonSerializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank(message: "El nombre de usuario no puede estar vacío.")]
    #[Assert\Length(
        max: 50,
        maxMessage: "El nombre de usuario no puede tener más de 50 caracteres."
    )]
    #[ORM\Column(length: 50)]
    private ?string $nom_usuari = null;

    #[Assert\NotBlank(message: "La contraseña no puede estar vacía.")]
    #[ORM\Column(length: 255)]
    private ?string $contrasenya = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message: "El nombre no puede estar vacío.")]
    #[Assert\Length(
        max: 50,
        maxMessage: "El nombre no puede tener más de 50 caracteres."
    )]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message: "El apellido no puede estar vacío.")]
    #[Assert\Length(
        max: 50,
        maxMessage: "El apellido no puede tener más de 50 caracteres."
    )]
    private ?string $cognom = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message: "El correo no puede estar vacío.")]
    #[Assert\Email(message: "Por favor, introduce un correo válido.")]
    #[Assert\Length(
        max: 50,
        maxMessage: "El correo no puede tener más de 50 caracteres."
    )]
    private ?string $correu = null;

    #[ORM\Column(type: Types::JSON)]
    #[Assert\NotNull(message: "El rol no puede estar vacío.")]
    private array $rols = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNomUsuari(): ?string
    {
        return $this->nom_usuari;
    }

    public function setNomUsuari(string $nom_usuari): static
    {
        $this->nom_usuari = $nom_usuari;

        return $this;
    }

    public function getContrasenya(): ?string
    {
        return $this->contrasenya;
    }

    public function setContrasenya(string $contrasenya): static
    {
        $this->contrasenya = $contrasenya;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCognom(): ?string
    {
        return $this->cognom;
    }

    public function setCognom(string $cognom): static
    {
        $this->cognom = $cognom;

        return $this;
    }

    public function getCorreu(): ?string
    {
        return $this->correu;
    }

    public function setCorreu(string $correu): static
    {
        $this->correu = $correu;

        return $this;
    }

    public function getRols(): array
    {
        return $this->rols;
    }

    public function setRols(array $rols): static
    {
        $this->rols = $rols;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->contrasenya;
    }

    public function getRoles(): array
    {
        return $this->rols;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getUserIdentifier(): string
    {
        return $this->getNomUsuari();
    }

    public function jsonSerialize(): mixed
    {
        return[
            "id" => $this->getId(),
            "nom_usuari" => $this->getNomUsuari(),
            "nom" => $this->getNom(),
            "cognom" => $this->getCognom(),
            "correu" => $this->getCorreu(),
            "rols" => $this->getRols(),
        ];
    }

}

templates/_aside_back.html.twig
<aside class="col-2 bg-blau border-end border-black aside">
    <h5 class="pt-4 text-center fw-bold">Panel de gestión</h5>
    <ul class="p-3 aside-list">
        <li class="pb-3 {{ app.request.attributes.get('_route') == 'app_home_back' ? 'active' : '' }}">
            <i class="bi bi-house"></i>
            <a href="{{ path('app_home_back') }}"
               class="link-dark link-offset-3 link-underline-opacity-0 link-underline-opacity-100-hover">
                Página principal
            </a>
        </li>
        {% if app.user and 'ROLE_ADMIN' in app.user.roles %}
            <li class="pb-3 {{ app.request.attributes.get('_route') == 'app_user_index' ? 'active' : '' }}">
                <i class="bi bi-people"></i>
                <a href="{{ path('app_user_index') }}"
                   class="link-dark link-offset-3 link-underline-opacity-0 link-underline-opacity-100-hover">
                    Usuarios
                </a>
            </li>
        {% endif %}
        <li class="pb-3 {{ app.request.attributes.get('_route') == 'app_client_index' ? 'active' : '' }}">
            <i class="bi bi-basket2"></i>
            <a href="{{ path('app_client_index') }}"
               class="link-dark link-offset-3 link-underline-opacity-0 link-underline-opacity-100-hover">
                Clientes
            </a>
        </li>
        <li class="pb-3 {{ app.request.attributes.get('_route') == 'app_obra_index' ? 'active' : '' }}">
            <i class="bi bi-book-half"></i>
            <a href="{{ path('app_obra_index') }}"
               class="link-dark link-offset-3 link-underline-opacity-0 link-underline-opacity-100-hover">
                Obras
            </a>
        </li>
        <li class="pb-3 {{ app.request.attributes.get('_route') == 'app_factura_index' ? 'active' : '' }}">
            <i class="bi bi-receipt"></i>
            <a href="{{ path('app_factura_index') }}"
               class="link-dark link-offset-3 link-underline-opacity-0 link-underline-opacity-100-hover">
                Facturas
            </a>
        </li>
        {% if app.user and 'ROLE_TREBALLADOR' in app.user.roles %}
            <li class="pb-3 {{ app.request.attributes.get('_route') == 'app_autopublicacio' ? 'active' : '' }}">
                <i class="bi bi-vector-pen"></i>
                <a href="{{ path('app_autopublicacio') }}"
                   class="link-dark link-offset-3 link-underline-opacity-0 link-underline-opacity-100-hover">
                    Autopublicació
                </a>
            </li>
        {% endif %}
    </ul>
</aside>

templates/_footer.html.twig
<footer class="py-1">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="d-flex justify-content-end align-items-center py-5">
					<p class="small">Copyright
						<i class="bi bi-c-circle"></i>
						<span class="text-taronja">NovelNest</span>. Todos los derechos reservados.</p>
				</div>
			</div>
		</div>
	</div>
</footer>

templates/_header.html.twig
<header>
    <nav class="navbar navbar-expand-lg bg-blau border-bottom border-black">
        <div class="container-fluid">
            <div class="d-flex align-items-center">
                <h1 class="text-logo">NovelNest</h1>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse ms-5" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {{ app.request.attributes.get('_route') == 'app_home' ? 'active' : '' }}"
                           aria-current="page" href="{{ path('app_home') }}">Página principal</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ app.request.attributes.get('_route') == 'app_contacte' ? 'active' : '' }}"
                           href="{{ path('app_contacte') }}">Contacto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ app.request.attributes.get('_route') == 'app_autopublicacio' ? 'active' : '' }}" href="{{ path('app_autopublicacio') }}">Autopublicación</a>
                    </li>
                    <li class="nav-item {{ app.request.attributes.get('_route') == 'app_biblioteca' ? 'active' : '' }}">
                        <a class="nav-link" href="{{ path('app_biblioteca') }}">Biblioteca</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ app.request.attributes.get('_route') == 'app_editors' ? 'active' : '' }}"
                           href="{{ path('app_editors') }}">Editores y editoras</a>
                    </li>
                    <li class="nav-item ms-2">
                        <a class="btn btn-dark rounded-circle" href="{{ path('app_carrito') }}"> <i class="bi bi-cart-fill"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="me-5">
                {% if app.user %}
                    {% if is_granted('ROLE_TREBALLADOR') %}
                        <a class="btn btn-outline-dark" href="{{ path('app_home_back') }}"><i class="bi bi-gear-fill fs-5"></i> Administración</a>
                    {% elseif is_granted('ROLE_CLIENT') %}
                        <a class="btn btn-outline-dark" href="{{ path('app_logout') }}"><i class="bi bi-box-arrow-right fs-5"></i> Salir</a>
                    {% endif %}
                {% else %}
                    <a class="btn btn-outline-dark" href="{{ path('app_login') }}"><i class="bi bi-person-circle"></i> Acceder</a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>

templates/_header_back.html.twig
<header>
    <nav class="bg-blau-back border-bottom py-2 border-bottom border-black">
        <div class="container-fluid d-flex justify-content-between align-items-center">
            {% if app.user %}
                <span class="text-dark pe-5">{{ app.user.getNomUsuari() }}</span>
            {% endif %}
            <div class="d-flex justify-content-center flex-grow-1">
                <h1 class="text-blau">NovelNest</h1>
            </div>
            {% if app.user and (is_granted('ROLE_ADMIN') or is_granted('ROLE_TREBALLADOR')) %}
                <a class="btn btn-outline-light" href="{{ path('app_logout') }}"><i class="bi bi-box-arrow-right fs-5"></i> Salir</a>
            {% endif %}
        </div>
    </nav>
</header>

templates/base.html.twig
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
          content="Si estás buscando autopublicar una novela, relato corto o poemario este sitio es ideal para ti. Y si además deseas descububir nuevas historias, aquí las podrás descubrir. ¡Adelante!">
    <title>
        {% block title %}NovelNest
        {% endblock %}
    </title>
    <link rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">

    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>
<body>

{% include '_header.html.twig' %}
{% block body %}
{% endblock %}
{% include '_footer.html.twig' %}

</body>
</html>

templates/base_back.html.twig
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}NovelNest
        {% endblock %}
    </title>
    <link rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">

    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}

</head>
<body>
{% include '_header_back.html.twig' %}
<main>
    <div class="container-fluid">
        <div class="row">
            {% include '_aside_back.html.twig' %}
            <div class="col-10">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </div>
</main>
</body>
</html>